name: my_flutter_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  visibility_detector: ^0.3.3
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  provider: ^6.0.5
  carousel_slider: ^5.0.0
  flutter_localizations:
    sdk: flutter
  vector_math: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0
  animated_bottom_navigation_bar: ^1.0.1
  convex_bottom_bar: ^3.0.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  badges: ^2.0.3
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/usama/
    - assets/usama/onboardingone.png
