// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL80NLQ8QchGdjKFMDlEcNc180rqxaIXs',
    appId: '1:799087638440:web:b68d5f3df4f9f519dc4f9d',
    messagingSenderId: '799087638440',
    projectId: 'flutter-pos-7d4e2',
    authDomain: 'flutter-pos-7d4e2.firebaseapp.com',
    storageBucket: 'flutter-pos-7d4e2.firebasestorage.app',
    measurementId: 'G-2ZHGGMJSST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAut9nZzInBNDvUorZMS7X0czTJJ0rIt8c',
    appId: '1:799087638440:android:dbd74963f8ed1938dc4f9d',
    messagingSenderId: '799087638440',
    projectId: 'flutter-pos-7d4e2',
    storageBucket: 'flutter-pos-7d4e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqkhEbWnitP0CoXu9PSBbmVMkAZNSQkIE',
    appId: '1:799087638440:ios:682ffb09c8656666dc4f9d',
    messagingSenderId: '799087638440',
    projectId: 'flutter-pos-7d4e2',
    storageBucket: 'flutter-pos-7d4e2.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqkhEbWnitP0CoXu9PSBbmVMkAZNSQkIE',
    appId: '1:799087638440:ios:682ffb09c8656666dc4f9d',
    messagingSenderId: '799087638440',
    projectId: 'flutter-pos-7d4e2',
    storageBucket: 'flutter-pos-7d4e2.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL80NLQ8QchGdjKFMDlEcNc180rqxaIXs',
    appId: '1:799087638440:web:d64850681bb1eee2dc4f9d',
    messagingSenderId: '799087638440',
    projectId: 'flutter-pos-7d4e2',
    authDomain: 'flutter-pos-7d4e2.firebaseapp.com',
    storageBucket: 'flutter-pos-7d4e2.firebasestorage.app',
    measurementId: 'G-RV9MEC7X0G',
  );
}
